"""Orders, from intent to fill.

The order state machine is total and explicit. An unmapped broker status
becomes :attr:`OrderStatus.UNKNOWN`, which halts trading on that instrument --
the engine never guesses a state in a money path.

``ClientOrderId`` is generated by the engine before anything is sent. It is the
idempotency key: a retry after a timeout carries the same id, so a broker that
already accepted the first attempt rejects the duplicate instead of placing a
second order.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from datetime import datetime
from enum import StrEnum
from typing import Final

from garuda.domain.calendar import require_aware
from garuda.domain.client import TradingClientId
from garuda.domain.enums import OrderStatus, OrderType, ProductType
from garuda.domain.errors import DomainError
from garuda.domain.instrument import InstrumentId
from garuda.domain.money import Money


class Side(StrEnum):
    """Which way an order goes.

    Distinct from ``Direction``: a side belongs to an order, a direction to a
    position. Selling to open and selling to close are the same side.
    """

    BUY = "BUY"
    SELL = "SELL"

    @property
    def opposite(self) -> Side:
        return Side.SELL if self is Side.BUY else Side.BUY

    @property
    def sign(self) -> int:
        return 1 if self is Side.BUY else -1


@dataclass(frozen=True, slots=True)
class ClientOrderId:
    """Engine-generated, unique, and the same across retries of one order."""

    value: str

    def __post_init__(self) -> None:
        if not self.value or self.value.strip() != self.value:
            raise DomainError(f"client order id {self.value!r} is empty or padded")

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True, slots=True)
class BrokerOrderId:
    """Whatever the broker calls the order. Opaque to the engine."""

    value: str

    def __post_init__(self) -> None:
        if not self.value:
            raise DomainError("broker order id is empty")

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True, slots=True)
class OrderRequest:
    """What the engine asks a broker to do.

    Prices are already quantized to the instrument's tick size by the time a
    request is built; the adapter translates, it does not round.
    """

    client_order_id: ClientOrderId
    trading_client: TradingClientId
    instrument: InstrumentId
    side: Side
    quantity: int
    order_type: OrderType
    product: ProductType
    price: Money | None = None
    trigger_price: Money | None = None
    tag: str | None = None

    def __post_init__(self) -> None:
        if self.quantity < 1:
            raise DomainError(f"{self.client_order_id}: quantity {self.quantity} must be positive")

        needs_price = self.order_type in (OrderType.LIMIT, OrderType.SL_LIMIT)
        needs_trigger = self.order_type in (OrderType.SL_LIMIT, OrderType.SL_MARKET)

        if needs_price and self.price is None:
            raise DomainError(f"{self.client_order_id}: {self.order_type} needs a price")
        if not needs_price and self.price is not None:
            raise DomainError(f"{self.client_order_id}: {self.order_type} takes no price")
        if needs_trigger and self.trigger_price is None:
            raise DomainError(f"{self.client_order_id}: {self.order_type} needs a trigger price")
        if not needs_trigger and self.trigger_price is not None:
            raise DomainError(f"{self.client_order_id}: {self.order_type} takes no trigger price")

        if self.price is not None and self.price.amount <= 0:
            raise DomainError(f"{self.client_order_id}: price {self.price} must be positive")
        if self.trigger_price is not None and self.trigger_price.amount <= 0:
            raise DomainError(
                f"{self.client_order_id}: trigger price {self.trigger_price} must be positive"
            )


@dataclass(frozen=True, slots=True)
class Fill:
    """One execution. Partial fills arrive as several."""

    client_order_id: ClientOrderId
    instrument: InstrumentId
    side: Side
    quantity: int
    price: Money
    timestamp: datetime
    broker_fill_id: str | None = None

    def __post_init__(self) -> None:
        require_aware(self.timestamp)
        if self.quantity < 1:
            raise DomainError(
                f"{self.client_order_id}: fill quantity {self.quantity} must be positive"
            )
        if self.price.amount <= 0:
            raise DomainError(f"{self.client_order_id}: fill price {self.price} must be positive")


#: Legal transitions. Anything absent here is a defect, not a surprise.
#:
#: UNKNOWN is reachable from every non-terminal state, because "the broker
#: stopped telling us" can happen at any moment. It is left only by
#: reconciliation against broker truth, never by inference.
ORDER_TRANSITIONS: Final[dict[OrderStatus, frozenset[OrderStatus]]] = {
    OrderStatus.PENDING_NEW: frozenset(
        {OrderStatus.NEW, OrderStatus.REJECTED, OrderStatus.UNKNOWN}
    ),
    OrderStatus.NEW: frozenset(
        {
            OrderStatus.PARTIALLY_FILLED,
            OrderStatus.FILLED,
            OrderStatus.PENDING_CANCEL,
            OrderStatus.PENDING_REPLACE,
            OrderStatus.CANCELLED,
            OrderStatus.REJECTED,
            OrderStatus.EXPIRED,
            OrderStatus.UNKNOWN,
        }
    ),
    OrderStatus.PARTIALLY_FILLED: frozenset(
        {
            OrderStatus.PARTIALLY_FILLED,
            OrderStatus.FILLED,
            OrderStatus.PENDING_CANCEL,
            OrderStatus.PENDING_REPLACE,
            OrderStatus.CANCELLED,
            OrderStatus.EXPIRED,
            OrderStatus.UNKNOWN,
        }
    ),
    OrderStatus.PENDING_CANCEL: frozenset(
        {
            OrderStatus.CANCELLED,
            OrderStatus.PARTIALLY_FILLED,
            OrderStatus.FILLED,
            OrderStatus.REJECTED,
            OrderStatus.UNKNOWN,
        }
    ),
    OrderStatus.PENDING_REPLACE: frozenset(
        {
            OrderStatus.NEW,
            OrderStatus.PARTIALLY_FILLED,
            OrderStatus.FILLED,
            OrderStatus.CANCELLED,
            OrderStatus.REJECTED,
            OrderStatus.UNKNOWN,
        }
    ),
    # Terminal.
    OrderStatus.FILLED: frozenset(),
    OrderStatus.CANCELLED: frozenset(),
    OrderStatus.REJECTED: frozenset(),
    OrderStatus.EXPIRED: frozenset(),
    # Left only by reconciliation, which can establish any real state.
    OrderStatus.UNKNOWN: frozenset(
        {
            OrderStatus.NEW,
            OrderStatus.PARTIALLY_FILLED,
            OrderStatus.FILLED,
            OrderStatus.CANCELLED,
            OrderStatus.REJECTED,
            OrderStatus.EXPIRED,
        }
    ),
}


class IllegalOrderTransitionError(DomainError):
    """A state change the order state machine does not allow."""


@dataclass(frozen=True, slots=True)
class Order:
    """An order and everything known about it so far."""

    request: OrderRequest
    status: OrderStatus = OrderStatus.PENDING_NEW
    broker_order_id: BrokerOrderId | None = None
    filled_quantity: int = 0
    average_fill_price: Money | None = None
    rejection_reason: str | None = None

    def __post_init__(self) -> None:
        if self.filled_quantity < 0:
            raise DomainError(f"{self.id}: filled quantity is negative")
        if self.filled_quantity > self.request.quantity:
            raise DomainError(
                f"{self.id}: filled {self.filled_quantity} exceeds ordered {self.request.quantity}"
            )

    @property
    def id(self) -> ClientOrderId:
        return self.request.client_order_id

    @property
    def instrument(self) -> InstrumentId:
        return self.request.instrument

    @property
    def remaining_quantity(self) -> int:
        return self.request.quantity - self.filled_quantity

    @property
    def is_terminal(self) -> bool:
        return self.status.is_terminal

    def can_transition_to(self, status: OrderStatus) -> bool:
        return status in ORDER_TRANSITIONS[self.status]

    def transition_to(self, status: OrderStatus, *, reason: str | None = None) -> Order:
        """Move to a new status, refusing anything the machine does not allow."""
        if not self.can_transition_to(status):
            raise IllegalOrderTransitionError(f"{self.id}: {self.status} cannot become {status}")
        return replace(self, status=status, rejection_reason=reason or self.rejection_reason)

    def accepted(self, broker_order_id: BrokerOrderId) -> Order:
        return replace(self.transition_to(OrderStatus.NEW), broker_order_id=broker_order_id)

    def apply_fill(self, fill: Fill) -> Order:
        """Fold one execution into the order.

        Fills accumulate into a quantity-weighted average, exactly. Rounding
        each fill instead would compound the error across a sliced entry.
        """
        if fill.client_order_id != self.id:
            raise DomainError(f"{self.id}: fill belongs to {fill.client_order_id}")
        if fill.side is not self.request.side:
            raise DomainError(f"{self.id}: fill side {fill.side} contradicts the order")

        filled = self.filled_quantity + fill.quantity
        if filled > self.request.quantity:
            raise DomainError(
                f"{self.id}: fill of {fill.quantity} would take filled quantity to "
                f"{filled}, above the ordered {self.request.quantity}"
            )

        if self.average_fill_price is None:
            average = fill.price
        else:
            value = self.average_fill_price * self.filled_quantity + fill.price * fill.quantity
            average = value / filled

        status = (
            OrderStatus.FILLED
            if filled == self.request.quantity
            else (OrderStatus.PARTIALLY_FILLED)
        )
        if not self.can_transition_to(status):
            raise IllegalOrderTransitionError(f"{self.id}: {self.status} cannot become {status}")

        return replace(self, status=status, filled_quantity=filled, average_fill_price=average)
