import type { CSSProperties } from 'react';

interface TradeModeBadgeProps {
  /** True when generated by a mock strategy (real broker, holiday mock session). */
  isMock?: boolean;
  /** True when the trade/signal belongs to a paper-trading subscription. */
  isPaperTrading?: boolean;
  /** Noun used in the tooltip, e.g. 'trade' | 'signal' | 'order' | 'position'. */
  noun?: string;
  className?: string;
  style?: CSSProperties;
}

/**
 * Single source of truth for the M / P / L mode badge shown next to a trade or
 * signal. Mock takes precedence over paper, paper over live (a trade is at most
 * one of these). M=warning / P=info / L=neutral. Migrated to the Tailwind
 * design system (tokens +  prefix).
 */
export function TradeModeBadge({ isMock, isPaperTrading, noun = 'trade', className = 'ml-1', style }: TradeModeBadgeProps) {
  const { letter, tone, label } = isMock
    ? { letter: 'M', tone: 'bg-warning-400 text-black', label: `Mock ${noun}` }
    : isPaperTrading
      ? { letter: 'P', tone: 'bg-accent-500/20 text-accent-600 dark:text-accent-400', label: `Paper ${noun}` }
      : { letter: 'L', tone: 'bg-raised text-ink-soft', label: `Live ${noun}` };

  return (
    <span
      className={`inline-flex items-center rounded px-1.5 py-0.5 text-[0.65rem] font-semibold ${tone} ${className}`}
      title={label}
      style={style}
    >
      {letter}
    </span>
  );
}
