"""initial schema

Revision ID: 4559d5b0a1b2
Revises:
Create Date: 2026-08-29 08:22:39.657883

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aggregated_pnl_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("snapshot_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_algo_pnl", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("total_broker_pnl", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("total_capital", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("total_external_capital", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("total_margin", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("total_utilized_margin", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aggregated_pnl_snapshots")),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("timestamp", sa.String(length=30), nullable=False),
        sa.Column("alert_level", sa.String(length=10), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_name", sa.String(length=100), nullable=True),
        sa.Column("operation", sa.String(length=50), nullable=True),
        sa.Column("alert_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_table(
        "allocation_model_strategies",
        sa.Column("model_name", sa.String(length=50), nullable=False),
        sa.Column("strategy_name", sa.String(length=30), nullable=False),
        sa.Column("num_of_lots", sa.Integer(), nullable=True),
        sa.Column("is_overlap_capital", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint(
            "model_name", "strategy_name", name=op.f("pk_allocation_model_strategies")
        ),
    )
    op.create_table(
        "allocation_models",
        sa.Column("model_name", sa.String(length=50), nullable=False),
        sa.Column("capital", sa.Integer(), nullable=False),
        sa.Column("intraday_capital", sa.Integer(), nullable=True),
        sa.Column("positional_capital", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("model_name", name=op.f("pk_allocation_models")),
    )
    op.create_table(
        "app_config",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_config")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("entity_name", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("old_data", sa.Text(), nullable=True),
        sa.Column("new_data", sa.Text(), nullable=True),
        sa.Column("changed_by", sa.String(length=100), nullable=False),
        sa.Column("changed_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_table(
        "broker_api_stats",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("broker_name", sa.String(length=30), nullable=False),
        sa.Column("operation", sa.String(length=50), nullable=True),
        sa.Column("order_id", sa.String(length=50), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_taken", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_api_stats")),
    )
    op.create_table(
        "broker_exchange_config",
        sa.Column("broker_name", sa.String(length=30), nullable=False),
        sa.Column("exchange_code", sa.String(length=10), nullable=False),
        sa.Column("login_minutes_before_market_open", sa.Integer(), nullable=True),
        sa.Column("intraday_squareoff_minutes_before_close", sa.Integer(), nullable=True),
        sa.Column("intraday_squareoff_block_minutes_before_close", sa.Integer(), nullable=True),
        sa.Column("market_orders_allowed", sa.Boolean(), nullable=True),
        sa.Column("naic_code", sa.String(length=8), nullable=True),
        sa.Column("algo_id", sa.String(length=32), nullable=True),
        sa.Column("limit_order_buffer_equity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("limit_order_buffer_futures", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("limit_order_buffer_options", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "sl_trigger_to_limit_gap_equity", sa.Numeric(precision=20, scale=6), nullable=False
        ),
        sa.Column(
            "sl_trigger_to_limit_gap_futures", sa.Numeric(precision=20, scale=6), nullable=False
        ),
        sa.Column(
            "sl_trigger_to_limit_gap_options", sa.Numeric(precision=20, scale=6), nullable=False
        ),
        sa.PrimaryKeyConstraint(
            "broker_name", "exchange_code", name=op.f("pk_broker_exchange_config")
        ),
    )
    op.create_table(
        "brokerage_plan_rates",
        sa.Column("plan_name", sa.String(length=30), nullable=False),
        sa.Column("segment", sa.String(length=20), nullable=False),
        sa.Column("product", sa.String(length=20), nullable=False),
        sa.Column("unit_type", sa.String(length=10), nullable=True),
        sa.Column("rate_per_unit", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("brokerage_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.PrimaryKeyConstraint(
            "plan_name", "segment", "product", name=op.f("pk_brokerage_plan_rates")
        ),
    )
    op.create_table(
        "brokerage_plans",
        sa.Column("plan_name", sa.String(length=30), nullable=False),
        sa.Column("unit_type", sa.String(length=10), nullable=True),
        sa.Column("brokerage_per_unit", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.Column("broker_name", sa.String(length=30), nullable=True),
        sa.Column("plan_type", sa.String(length=20), nullable=True),
        sa.Column("fixed_fee", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("billing_period", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("plan_name", name=op.f("pk_brokerage_plans")),
    )
    op.create_table(
        "brokers",
        sa.Column("broker_name", sa.String(length=30), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("stopped", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.Column("provider", sa.String(length=30), nullable=True),
        sa.Column("use_dealer_apis", sa.Boolean(), nullable=True),
        sa.Column("server_url", sa.String(length=100), nullable=True),
        sa.Column("data_server_url", sa.String(length=100), nullable=True),
        sa.Column("bo_co_blocked", sa.Boolean(), nullable=True),
        sa.Column("market_data_app_key", sa.String(length=50), nullable=True),
        sa.Column("market_data_app_secret", sa.String(length=50), nullable=True),
        sa.Column("web_socket_enabled", sa.Boolean(), nullable=True),
        sa.Column("api_version", sa.Integer(), nullable=True),
        sa.Column("server_start_time", sa.String(length=5), nullable=True),
        sa.Column("server_stop_time", sa.String(length=5), nullable=True),
        sa.Column("naic_code", sa.String(length=8), nullable=True),
        sa.Column("algo_id", sa.String(length=32), nullable=True),
        sa.Column("oauth_url", sa.String(length=250), nullable=True),
        sa.Column("host_lookup_version", sa.String(length=50), nullable=True),
        sa.Column("order_update_interval_secs", sa.Integer(), nullable=False),
        sa.Column("position_update_interval_secs", sa.Integer(), nullable=False),
        sa.Column("host_lookup_path", sa.String(length=100), nullable=True),
        sa.Column("iosocket_version", sa.String(length=10), nullable=True),
        sa.Column("mtf_interest_rate_per_annum", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.PrimaryKeyConstraint("broker_name", name=op.f("pk_brokers")),
    )
    op.create_table(
        "client_pnl_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("broker", sa.String(length=50), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("snapshot_timestamp", sa.BigInteger(), nullable=False),
        sa.Column("algo_pnl", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("broker_pnl", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("capital", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("total_margin", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("utilized_margin", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_pnl_snapshots")),
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("exchange", sa.String(length=16), nullable=False),
        sa.Column("trading_symbol", sa.String(length=64), nullable=False),
        sa.Column("action_type", sa.String(length=16), nullable=False),
        sa.Column("ratio_from", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("ratio_to", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("qty_factor", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.String(length=512), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_actions")),
    )
    op.create_table(
        "daily_symbol_close_prices",
        sa.Column("exchange", sa.String(length=15), nullable=False),
        sa.Column("trading_symbol", sa.String(length=50), nullable=False),
        sa.Column("close_date", sa.Date(), nullable=False),
        sa.Column("close_price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "exchange", "trading_symbol", "close_date", name=op.f("pk_daily_symbol_close_prices")
        ),
    )
    op.create_table(
        "data_provider_sessions",
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("client_id", sa.String(length=50), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("provider", name=op.f("pk_data_provider_sessions")),
    )
    op.create_table(
        "event_days",
        sa.Column("event_date", sa.String(length=10), nullable=False),
        sa.Column("exchange_code", sa.String(length=10), nullable=False),
        sa.Column("event_name", sa.String(length=100), nullable=True),
        sa.Column("bo_co_blocked", sa.Boolean(), nullable=True),
        sa.Column("capital_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.PrimaryKeyConstraint("event_date", "exchange_code", name=op.f("pk_event_days")),
    )
    # Written by hand: autogenerate cannot express PARTITION BY, and PostgreSQL
    # requires the partition key in every unique constraint. A DEFAULT
    # partition means nothing ever fails to insert because a dated partition
    # was missing; dated ones can be attached later.
    op.execute(sa.text("CREATE SEQUENCE event_journal_sequence_seq AS bigint"))
    op.execute(
        sa.text(
            """
            CREATE TABLE event_journal (
                trading_day    date        NOT NULL,
                sequence       bigint      NOT NULL
                                           DEFAULT nextval('event_journal_sequence_seq'),
                event_type     varchar(64) NOT NULL,
                aggregate_type varchar(64) NOT NULL,
                aggregate_id   varchar(255) NOT NULL,
                occurred_at    timestamptz NOT NULL,
                actor          varchar(64) NOT NULL,
                payload        jsonb       NOT NULL,
                correlation_id varchar(64),
                CONSTRAINT pk_event_journal PRIMARY KEY (trading_day, sequence)
            ) PARTITION BY RANGE (trading_day)
            """
        )
    )
    op.execute(sa.text("ALTER SEQUENCE event_journal_sequence_seq OWNED BY event_journal.sequence"))
    op.execute(sa.text("CREATE TABLE event_journal_default PARTITION OF event_journal DEFAULT"))
    op.create_index(
        "ix_event_journal_aggregate",
        "event_journal",
        ["aggregate_type", "aggregate_id", "trading_day"],
        unique=False,
    )
    op.create_index(
        "ix_event_journal_correlation", "event_journal", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_event_journal_type_day", "event_journal", ["event_type", "trading_day"], unique=False
    )
    op.create_table(
        "exchanges",
        sa.Column("exchange_code", sa.String(length=10), nullable=False),
        sa.Column("exchange_name", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("pre_market_start", sa.Time(), nullable=True),
        sa.Column("pre_market_end", sa.Time(), nullable=True),
        sa.Column("market_open", sa.Time(), nullable=False),
        sa.Column("market_close", sa.Time(), nullable=False),
        sa.Column("intraday_squareoff_minutes_before_close", sa.Integer(), nullable=True),
        sa.Column("intraday_squareoff_block_minutes_before_close", sa.Integer(), nullable=True),
        sa.Column("post_market_window_minutes", sa.Integer(), nullable=True),
        sa.Column("report_minutes_after_close", sa.Integer(), nullable=True),
        sa.Column("history_cache_enabled", sa.Boolean(), nullable=True),
        sa.Column("weekend_days", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("day_init_minutes_before_market_open", sa.Integer(), nullable=True),
        sa.Column("algo_start_minutes_before_market_open", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("exchange_code", name=op.f("pk_exchanges")),
    )
    op.create_table(
        "exit_policy",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("policy_name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("exit_mode", sa.String(length=20), nullable=True),
        sa.Column("exit_days", sa.Integer(), nullable=True),
        sa.Column("exit_time", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exit_policy")),
    )
    op.create_table(
        "hedge_schedules",
        sa.Column("schedule_id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("window_type", sa.String(length=16), nullable=False),
        sa.Column("window_start", sa.Time(), nullable=False),
        sa.Column("window_end", sa.Time(), nullable=False),
        sa.Column("hedge_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("schedule_id", name=op.f("pk_hedge_schedules")),
    )
    op.create_table(
        "holidays",
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("date", "exchange", name=op.f("pk_holidays")),
    )
    op.create_table(
        "iv_candles",
        sa.Column("symbol", sa.String(length=25), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ce_iv_open", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("ce_iv_high", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("ce_iv_low", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("ce_iv_close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pe_iv_open", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pe_iv_high", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pe_iv_low", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pe_iv_close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("ce_strike", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pe_strike", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("spot_close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "timestamp", name=op.f("pk_iv_candles")),
    )
    op.create_table(
        "kill_switch_types",
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("source", name=op.f("pk_kill_switch_types")),
    )
    op.create_table(
        "order_fill_escalation_policy",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("policy_name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("escalation_mode", sa.String(length=20), nullable=False),
        sa.Column("escalation_seconds", sa.Integer(), nullable=True),
        sa.Column("escalation_steps", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_fill_escalation_policy")),
    )
    op.create_table(
        "pcr_candles",
        sa.Column("symbol", sa.String(length=25), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pcr_open", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pcr_high", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pcr_low", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pcr_close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("put_oi", sa.BigInteger(), nullable=True),
        sa.Column("call_oi", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "timestamp", name=op.f("pk_pcr_candles")),
    )
    op.create_table(
        "products",
        sa.Column("product", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("product", name=op.f("pk_products")),
    )
    op.create_table(
        "rms_breach_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("breach_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("strategy_name", sa.String(length=100), nullable=True),
        sa.Column("trading_symbol", sa.String(length=100), nullable=True),
        sa.Column("exchange", sa.String(length=10), nullable=True),
        sa.Column("breach_type", sa.String(length=50), nullable=True),
        sa.Column("breach_category", sa.String(length=20), nullable=True),
        sa.Column("breach_details", sa.Text(), nullable=True),
        sa.Column("action_taken", sa.String(length=50), nullable=True),
        sa.Column("current_value", sa.String(length=50), nullable=True),
        sa.Column("limit_value", sa.String(length=50), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rms_breach_log")),
    )
    op.create_table(
        "rms_client_state",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("broker", sa.String(length=50), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("deployed_capital", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("used_margin", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("available_margin", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("peak_margin_used", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("unrealized_pnl", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("total_pnl", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("peak_pnl", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("drawdown", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("total_positions", sa.Integer(), nullable=True),
        sa.Column("gross_exposure", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("net_exposure", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("orders_today", sa.Integer(), nullable=True),
        sa.Column("rejections_today", sa.Integer(), nullable=True),
        sa.Column("consecutive_losses", sa.Integer(), nullable=True),
        sa.Column("is_killed", sa.Boolean(), nullable=True),
        sa.Column("kill_reason", sa.String(length=200), nullable=True),
        sa.Column("kill_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rms_client_state")),
    )
    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=True),
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("breakout_level", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("breakout_level_dt0", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("breakout_level_dt1", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("breakout_level_dt2", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("breakout_direction", sa.String(length=10), nullable=True),
        sa.Column("is_breakout_level_in_percentage", sa.Boolean(), nullable=True),
        sa.Column("breakout_valid_range", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("from_timestamp", sa.String(length=12), nullable=True),
        sa.Column("from_last_n_mins", sa.Integer(), nullable=True),
        sa.Column("from_level", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rules")),
    )
    op.create_table(
        "sl_target_policy",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("policy_name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("sl_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("target_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("combined_sl_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("combined_target_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column(
            "sl_trigger_to_limit_gap_percentage", sa.Numeric(precision=20, scale=6), nullable=True
        ),
        sa.Column("sl_buffer_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("risk_calculation_mode", sa.String(length=30), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sl_target_policy")),
    )
    op.create_table(
        "statutory_charges",
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("segment", sa.String(length=20), nullable=False),
        sa.Column("product", sa.String(length=20), nullable=False),
        sa.Column("stt_buy_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("stt_sell_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("exchange_txn_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("sebi_charges_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("stamp_duty_buy_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("stamp_duty_sell_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("gst_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("depository_charges", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "exchange", "segment", "product", name=op.f("pk_statutory_charges")
        ),
    )
    op.create_table(
        "statutory_charges_broker_overrides",
        sa.Column("broker_name", sa.String(length=30), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("segment", sa.String(length=20), nullable=False),
        sa.Column("product", sa.String(length=20), nullable=False),
        sa.Column("stt_buy_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("stt_sell_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("exchange_txn_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("sebi_charges_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("stamp_duty_buy_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("stamp_duty_sell_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("gst_pct", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("depository_charges", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "broker_name",
            "exchange",
            "segment",
            "product",
            name=op.f("pk_statutory_charges_broker_overrides"),
        ),
    )
    op.create_table(
        "stock_universe_members",
        sa.Column("universe_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("universe_id", "symbol", name=op.f("pk_stock_universe_members")),
    )
    op.create_table(
        "stock_universes",
        sa.Column("universe_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("universe_type", sa.String(length=20), nullable=False),
        sa.Column("index_key", sa.String(length=40), nullable=True),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("universe_id", name=op.f("pk_stock_universes")),
    )
    op.create_table(
        "straddle_candles",
        sa.Column("symbol", sa.String(length=25), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "timestamp", name=op.f("pk_straddle_candles")),
    )
    op.create_table(
        "strategy_breakout_watches",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("watch_type", sa.String(length=20), nullable=False),
        sa.Column("watch_symbol", sa.String(length=100), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("reference_price", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("trigger_price_above", sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column("trigger_price_below", sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("trigger_mode", sa.String(length=15), nullable=False),
        sa.Column("trigger_value", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("broker_name", sa.String(length=50), nullable=False),
        sa.Column("tranch_number", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.String(length=50), nullable=True),
        sa.Column("valid_till", sa.Time(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_triggered", sa.Boolean(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_price", sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column("is_expired", sa.Boolean(), nullable=False),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trading_symbol", sa.String(length=100), nullable=True),
        sa.Column("option_type", sa.String(length=5), nullable=True),
        sa.Column("strike", sa.Integer(), nullable=True),
        sa.Column("trade_direction", sa.String(length=10), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("quantity_per_lot", sa.Integer(), nullable=True),
        sa.Column("entry_premium", sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column("fno_symbol", sa.String(length=50), nullable=True),
        sa.Column("strike_type", sa.String(length=20), nullable=True),
        sa.Column("strike_value", sa.String(length=20), nullable=True),
        sa.Column("option_premium", sa.Integer(), nullable=True),
        sa.Column("option_premium_upper", sa.Integer(), nullable=True),
        sa.Column("is_directional", sa.Boolean(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("risk_used_estimate", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_breakout_watches")),
    )
    op.create_table(
        "strategy_config",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "priority",
            sa.Integer(),
            sa.Computed(
                "(CASE WHEN tranch_number IS NOT NULL THEN 2 ELSE 0 END) + (CASE WHEN day_condition IS NOT NULL THEN 1 ELSE 0 END)",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("tranch_number", sa.Integer(), nullable=True),
        sa.Column("day_condition", sa.String(length=20), nullable=True),
        sa.Column("strike_type", sa.String(length=30), nullable=True),
        sa.Column("strike_value", sa.String(length=20), nullable=True),
        sa.Column("option_premium", sa.Integer(), nullable=True),
        sa.Column("option_premium_upper", sa.Integer(), nullable=True),
        sa.Column("use_atm_if_itm", sa.Boolean(), nullable=True),
        sa.Column("volume_filter", sa.BigInteger(), nullable=True),
        sa.Column("oi_filter", sa.BigInteger(), nullable=True),
        sa.Column("apply_volume_filter_to_hedge", sa.Boolean(), nullable=True),
        sa.Column("apply_oi_filter_to_hedge", sa.Boolean(), nullable=True),
        sa.Column("lots_per_tranch", sa.Integer(), nullable=True),
        sa.Column("hedging_enabled", sa.Boolean(), nullable=True),
        sa.Column("sl_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("target_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("combined_sl_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("combined_target_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("risk_calculation_mode", sa.String(length=30), nullable=True),
        sa.Column("trail_sl", sa.Boolean(), nullable=True),
        sa.Column("trail_sl_type", sa.String(length=20), nullable=True),
        sa.Column("trail_config", sa.Text(), nullable=True),
        sa.Column("sl_buffer_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("trail_sl_to_cost", sa.Boolean(), nullable=True),
        sa.Column("combined_trail_sl", sa.Boolean(), nullable=True),
        sa.Column(
            "sl_trigger_to_limit_gap_percentage", sa.Numeric(precision=20, scale=6), nullable=True
        ),
        sa.Column("tranch_timing", sa.String(length=10), nullable=True),
        sa.Column("tranch_cutoff_time", sa.String(length=10), nullable=True),
        sa.Column("min_tranch_gap", sa.Integer(), nullable=True),
        sa.Column("tranch_gap", sa.Integer(), nullable=True),
        sa.Column("exit_mode", sa.String(length=50), nullable=True),
        sa.Column("exit_days", sa.Integer(), nullable=True),
        sa.Column("exit_time", sa.String(length=20), nullable=True),
        sa.Column("order_fill_escalation_mode", sa.String(length=20), nullable=True),
        sa.Column("order_fill_escalation_seconds", sa.Integer(), nullable=True),
        sa.Column("order_fill_escalation_steps", sa.Text(), nullable=True),
        sa.Column("max_tranches", sa.Integer(), nullable=True),
        sa.Column("lot_allocation_mode", sa.String(length=20), nullable=True),
        sa.Column("global_allocation_tranches", sa.Integer(), nullable=True),
        sa.Column("allocation_start_tranch", sa.Integer(), nullable=True),
        sa.Column("re_entry", sa.Boolean(), nullable=True),
        sa.Column("max_reentries", sa.Integer(), nullable=True),
        sa.Column("min_reentry_loss_percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("directional", sa.Boolean(), nullable=True),
        sa.Column("breakout_enabled", sa.Boolean(), nullable=True),
        sa.Column("breakout_watch_type", sa.String(length=20), nullable=True),
        sa.Column("breakout_direction", sa.String(length=10), nullable=True),
        sa.Column("breakout_trigger_mode", sa.String(length=15), nullable=True),
        sa.Column("breakout_trigger_value", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("breakout_select_fresh_strikes", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "hedge_strike_rounding_min_distance", sa.Numeric(precision=20, scale=6), nullable=True
        ),
        sa.Column("oi_rank", sa.Integer(), nullable=True),
        sa.Column("ignore_itm_strikes", sa.Boolean(), nullable=True),
        sa.Column("lookback_minutes", sa.Integer(), nullable=True),
        sa.Column("otm_levels", sa.Integer(), nullable=True),
        sa.Column("no_stop_loss", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_config")),
        sa.UniqueConstraint(
            "strategy_name", "tranch_number", "day_condition", name="uq_strategy_config_scope"
        ),
    )
    op.create_table(
        "strategy_definitions",
        sa.Column("strategy_id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("template_name", sa.String(length=100), nullable=True),
        sa.Column("underlying_symbol", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=20), nullable=False),
        sa.Column("product", sa.String(length=16), nullable=True),
        sa.Column("trade_mode", sa.String(length=20), nullable=False),
        sa.Column("tick_trigger_enabled", sa.Boolean(), nullable=True),
        sa.Column("scheduled_trigger_enabled", sa.Boolean(), nullable=True),
        sa.Column("signal_trigger_enabled", sa.Boolean(), nullable=True),
        sa.Column("periodic_trigger_enabled", sa.Boolean(), nullable=True),
        sa.Column("start_time", sa.String(length=10), nullable=True),
        sa.Column("stop_time", sa.String(length=10), nullable=True),
        sa.Column("tradable_days", sa.String(length=200), nullable=True),
        sa.Column("excluded_days", sa.String(length=100), nullable=True),
        sa.Column("capital_per_lot", sa.Integer(), nullable=True),
        sa.Column("capital_per_lot_hedged", sa.Integer(), nullable=True),
        sa.Column("capital_per_lot_naked", sa.Integer(), nullable=True),
        sa.Column("is_overlap_capital", sa.Boolean(), nullable=True),
        sa.Column("expiry_type", sa.String(length=16), nullable=True),
        sa.Column("exclude_monthly_expiry", sa.Boolean(), nullable=False),
        sa.Column("use_premium_balancing", sa.Boolean(), nullable=False),
        sa.Column("underlying_type", sa.String(length=20), nullable=True),
        sa.Column(
            "hedge_distance_percentage_intraday", sa.Numeric(precision=20, scale=6), nullable=True
        ),
        sa.Column(
            "hedge_distance_percentage_positional", sa.Numeric(precision=20, scale=6), nullable=True
        ),
        sa.Column("is_directional", sa.Boolean(), nullable=True),
        sa.Column("direction_provider_type", sa.String(length=50), nullable=True),
        sa.Column("direction_provider_params", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("catch_up_missed_tranches", sa.Boolean(), nullable=False),
        sa.Column("adaptive_tranches_enabled", sa.Boolean(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("scope", sa.String(length=10), nullable=True),
        sa.Column("periodic_interval_minutes", sa.Integer(), nullable=True),
        sa.Column("periodic_offset_seconds", sa.Integer(), nullable=True),
        sa.Column("hedge_replace_enabled", sa.Boolean(), nullable=True),
        sa.Column("hedge_morning_start_offset", sa.Integer(), nullable=True),
        sa.Column("hedge_morning_end_offset", sa.Integer(), nullable=True),
        sa.Column("hedge_evening_start_offset", sa.Integer(), nullable=True),
        sa.Column("hedge_evening_end_offset", sa.Integer(), nullable=True),
        sa.Column("risk_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("absolute_max_risk", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("min_risk_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("max_risk_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("leverage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("min_leverage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("max_leverage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("universe_id", sa.BigInteger(), nullable=True),
        sa.Column("equity_sizing_model", sa.String(length=30), nullable=True),
        sa.Column("fixed_amount_per_stock", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("max_active_positions", sa.Integer(), nullable=True),
        sa.Column("max_risk_pct_per_trade", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("on_index_removal", sa.String(length=20), nullable=True),
        sa.Column("combo_spec_json", sa.Text(), nullable=True),
        sa.Column("entry_leg_order", sa.String(length=32), nullable=True),
        sa.Column("exit_leg_order", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("strategy_id", name=op.f("pk_strategy_definitions")),
    )
    op.create_table(
        "strategy_indicator_rules",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("entry_rules_json", sa.Text(), nullable=True),
        sa.Column("direction_rules_json", sa.Text(), nullable=True),
        sa.Column("exit_rules_json", sa.Text(), nullable=True),
        sa.Column("use_indicator_exit", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_indicator_rules")),
    )
    op.create_table(
        "strategy_rules_map",
        sa.Column("strategy_name", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("cond", sa.String(length=20), nullable=False),
        sa.Column("rules_expr", sa.String(length=100), nullable=True),
        sa.Column("depends_on_cond", sa.String(length=20), nullable=True),
        sa.Column("tranches", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint(
            "strategy_name", "exchange", "cond", "tranches", name=op.f("pk_strategy_rules_map")
        ),
    )
    op.create_table(
        "strategy_rules_output",
        sa.Column("strategy_name", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("tranches", sa.String(length=100), nullable=False),
        sa.Column("cond", sa.String(length=20), nullable=False),
        sa.Column("symbol_list", sa.String(length=200), nullable=True),
        sa.Column("price_list", sa.String(length=200), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "strategy_name", "exchange", "tranches", "cond", name=op.f("pk_strategy_rules_output")
        ),
    )
    op.create_table(
        "strategy_symbol_subscriptions",
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=20), nullable=False),
        sa.Column("subscription_type", sa.String(length=16), nullable=False),
        sa.Column("strikes_above", sa.Integer(), nullable=True),
        sa.Column("strikes_below", sa.Integer(), nullable=True),
        sa.Column("expiry_type", sa.String(length=16), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("subscription_id", name=op.f("pk_strategy_symbol_subscriptions")),
    )
    op.create_table(
        "strategy_templates",
        sa.Column("template_name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("evaluator_class", sa.String(length=500), nullable=False),
        sa.Column("supports_tick_trigger", sa.Boolean(), nullable=True),
        sa.Column("supports_scheduled_trigger", sa.Boolean(), nullable=True),
        sa.Column("supports_signal_trigger", sa.Boolean(), nullable=True),
        sa.Column("supports_periodic_trigger", sa.Boolean(), nullable=True),
        sa.Column("supports_hedge_management", sa.Boolean(), nullable=True),
        sa.Column("is_fno", sa.Boolean(), nullable=True),
        sa.Column("support_tranches", sa.Boolean(), nullable=True),
        sa.Column("default_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("asset_class", sa.String(length=10), nullable=False),
        sa.Column("is_user_selectable", sa.Boolean(), nullable=False),
        sa.Column("supported_trade_modes", sa.String(length=100), nullable=True),
        sa.Column("supported_direction_providers", sa.String(length=255), nullable=True),
        sa.Column("supports_indicator_entry", sa.Boolean(), nullable=False),
        sa.Column("supports_indicator_exit", sa.Boolean(), nullable=False),
        sa.Column("supports_reentry", sa.Boolean(), nullable=False),
        sa.Column("resolution_priority", sa.Integer(), nullable=False),
        sa.Column("supports_combos", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("template_name", name=op.f("pk_strategy_templates")),
    )
    op.create_table(
        "strike_selection_policy",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("policy_name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("strike_type", sa.String(length=20), nullable=True),
        sa.Column("strike_value", sa.String(length=20), nullable=True),
        sa.Column("premium_lower", sa.Integer(), nullable=True),
        sa.Column("premium_upper", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strike_selection_policy")),
    )
    op.create_table(
        "symbol_broker_info",
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("broker_name", sa.String(length=30), nullable=False),
        sa.Column("freeze_limit_qty", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "broker_name", name=op.f("pk_symbol_broker_info")),
    )
    op.create_table(
        "symbols",
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("exchange", sa.String(length=15), nullable=True),
        sa.Column("index_symbol", sa.String(length=50), nullable=True),
        sa.Column("is_index", sa.Boolean(), nullable=True),
        sa.Column("strike_gap", sa.Integer(), nullable=True),
        sa.Column("freeze_limit_qty", sa.Integer(), nullable=True),
        sa.Column("max_option_chain_levels", sa.Integer(), nullable=True),
        sa.Column("has_options_weekly_expiry", sa.Boolean(), nullable=True),
        sa.Column("has_options_monthly_expiry", sa.Boolean(), nullable=True),
        sa.Column("has_futures_weekly_expiry", sa.Boolean(), nullable=True),
        sa.Column("has_futures_monthly_expiry", sa.Boolean(), nullable=True),
        sa.Column("straddle_max_premium_diff", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("contract_multiplier", sa.Integer(), nullable=True),
        sa.Column("hedge_strike_rounding_multiple", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_symbols")),
    )
    op.create_table(
        "synthetic_candles",
        sa.Column("symbol", sa.String(length=25), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "timestamp", name=op.f("pk_synthetic_candles")),
    )
    op.create_table(
        "trade_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("trade_id", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("broker", sa.String(length=32), nullable=False),
        sa.Column("strategy", sa.String(length=128), nullable=True),
        sa.Column("trading_symbol", sa.String(length=64), nullable=True),
        sa.Column("hedge_correlation_id", sa.String(length=64), nullable=True),
        sa.Column("event_category", sa.String(length=24), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=True),
        sa.Column("order_status", sa.String(length=32), nullable=True),
        sa.Column("order_type", sa.String(length=16), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("filled_quantity", sa.Integer(), nullable=True),
        sa.Column("sl_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("target_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_log")),
    )
    op.create_table(
        "trading_clients",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("broker", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=True),
        sa.Column("api_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("redirect_url", sa.String(length=500), nullable=True),
        sa.Column("static_ip", sa.String(length=45), nullable=True),
        sa.Column("is_pro", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("use_dealer_apis", sa.Boolean(), nullable=True),
        sa.Column("websocket_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_clients")),
        sa.UniqueConstraint("broker", "client_id", name="uq_trading_clients_account"),
        sa.UniqueConstraint("display_name", name=op.f("uq_trading_clients_display_name")),
    )
    op.create_table(
        "trailing_sl_policy",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("policy_name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("trail_enabled", sa.Boolean(), nullable=True),
        sa.Column("trail_type", sa.String(length=20), nullable=True),
        sa.Column("trail_config", sa.Text(), nullable=True),
        sa.Column("trail_to_cost", sa.Boolean(), nullable=True),
        sa.Column("combined_trail_enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trailing_sl_policy")),
    )
    op.create_table(
        "capital_change_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_name", sa.String(length=30), nullable=False),
        sa.Column("old_capital", sa.Integer(), nullable=True),
        sa.Column("new_capital", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_capital_change_history_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capital_change_history")),
    )
    op.create_index(
        op.f("ix_capital_change_history_trading_client_id"),
        "capital_change_history",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "client_capital",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("capital", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_client_capital_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("trading_client_id", "date", name=op.f("pk_client_capital")),
    )
    op.create_index(
        op.f("ix_client_capital_trading_client_id"),
        "client_capital",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "client_margins",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("exchange_code", sa.String(length=10), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("peak_margin", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("total_margin", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_client_margins_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("trading_client_id", "date", name=op.f("pk_client_margins")),
    )
    op.create_index(
        op.f("ix_client_margins_trading_client_id"),
        "client_margins",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "eod_pnl_reports",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("strategy_name", sa.String(length=30), nullable=False),
        sa.Column("product", sa.String(length=50), nullable=False),
        sa.Column("capital", sa.Integer(), nullable=True),
        sa.Column("profit_loss", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("charges", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("net_profit_loss", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=False),
        sa.Column("mtf_interest", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_eod_pnl_reports_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "trading_client_id",
            "date",
            "strategy_name",
            "product",
            "is_paper_trading",
            name=op.f("pk_eod_pnl_reports"),
        ),
    )
    op.create_index(
        op.f("ix_eod_pnl_reports_trading_client_id"),
        "eod_pnl_reports",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "kill_switches",
        sa.Column("trading_client_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_date", sa.Date(), nullable=False),
        sa.Column("key_name", sa.String(length=255), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=50), nullable=True),
        sa.Column("symbol", sa.String(length=100), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("clear_time_abs_loss", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_kill_switches_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kill_switches")),
    )
    op.create_index(
        op.f("ix_kill_switches_trading_client_id"),
        "kill_switches",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "live_trade_signals",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("signal_id", sa.String(length=50), nullable=False),
        sa.Column("product", sa.String(length=15), nullable=False),
        sa.Column("strategy_name", sa.String(length=64), nullable=True),
        sa.Column("trading_symbol", sa.String(length=50), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=True),
        sa.Column("is_triggered", sa.Boolean(), nullable=False),
        sa.Column("is_disabled", sa.Boolean(), nullable=False),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=False),
        sa.Column("signal_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trade_group", sa.String(length=64), nullable=True),
        sa.Column("tranch", sa.Integer(), nullable=False),
        sa.Column("slice", sa.Integer(), nullable=False),
        sa.Column("evicted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_live_trade_signals_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("signal_id", name=op.f("pk_live_trade_signals")),
    )
    op.create_index(
        op.f("ix_live_trade_signals_trading_client_id"),
        "live_trade_signals",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "live_trade_signals_archive",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("signal_id", sa.String(length=50), nullable=False),
        sa.Column("product", sa.String(length=15), nullable=False),
        sa.Column("strategy_name", sa.String(length=64), nullable=True),
        sa.Column("trading_symbol", sa.String(length=50), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=True),
        sa.Column("is_triggered", sa.Boolean(), nullable=False),
        sa.Column("is_disabled", sa.Boolean(), nullable=False),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=False),
        sa.Column("signal_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trade_group", sa.String(length=64), nullable=True),
        sa.Column("tranch", sa.Integer(), nullable=False),
        sa.Column("slice", sa.Integer(), nullable=False),
        sa.Column("evicted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_live_trade_signals_archive_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("signal_id", name=op.f("pk_live_trade_signals_archive")),
    )
    op.create_index(
        op.f("ix_live_trade_signals_archive_trading_client_id"),
        "live_trade_signals_archive",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "live_trades",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("trade_id", sa.String(length=50), nullable=False),
        sa.Column("product", sa.String(length=15), nullable=False),
        sa.Column("strategy_name", sa.String(length=64), nullable=True),
        sa.Column("trading_symbol", sa.String(length=50), nullable=True),
        sa.Column("signal_id", sa.String(length=50), nullable=True),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=False),
        sa.Column("start_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("hedge_correlation_id", sa.String(length=50), nullable=True),
        sa.Column("pair_correlation_id", sa.String(length=50), nullable=True),
        sa.Column("trade_group", sa.String(length=64), nullable=True),
        sa.Column("tranch", sa.Integer(), nullable=False),
        sa.Column("slice", sa.Integer(), nullable=False),
        sa.Column("evicted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_live_trades_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("trade_id", name=op.f("pk_live_trades")),
    )
    op.create_index(
        op.f("ix_live_trades_trading_client_id"), "live_trades", ["trading_client_id"], unique=False
    )
    op.create_table(
        "live_trades_archive",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("trade_id", sa.String(length=50), nullable=False),
        sa.Column("product", sa.String(length=15), nullable=False),
        sa.Column("strategy_name", sa.String(length=64), nullable=True),
        sa.Column("trading_symbol", sa.String(length=50), nullable=True),
        sa.Column("signal_id", sa.String(length=50), nullable=True),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=False),
        sa.Column("start_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("hedge_correlation_id", sa.String(length=50), nullable=True),
        sa.Column("pair_correlation_id", sa.String(length=50), nullable=True),
        sa.Column("trade_group", sa.String(length=64), nullable=True),
        sa.Column("tranch", sa.Integer(), nullable=False),
        sa.Column("slice", sa.Integer(), nullable=False),
        sa.Column("evicted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_live_trades_archive_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("trade_id", name=op.f("pk_live_trades_archive")),
    )
    op.create_index(
        op.f("ix_live_trades_archive_trading_client_id"),
        "live_trades_archive",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "rms_config",
        sa.Column("trading_client_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("config_level", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=True),
        sa.Column("symbol", sa.String(length=50), nullable=True),
        sa.Column("segment_type", sa.String(length=20), nullable=True),
        sa.Column("min_volume_today", sa.Integer(), nullable=True),
        sa.Column("min_volume_early_market", sa.Integer(), nullable=True),
        sa.Column("max_bid_ask_spread_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("max_bid_ask_spread_absolute", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "bid_ask_absolute_threshold_price", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("min_depth_quantity", sa.Integer(), nullable=True),
        sa.Column("min_depth_levels", sa.Integer(), nullable=True),
        sa.Column("enable_freak_price_check", sa.Boolean(), nullable=True),
        sa.Column("freak_check_min_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("max_order_qty", sa.Integer(), nullable=True),
        sa.Column("max_order_qty_lots", sa.Integer(), nullable=True),
        sa.Column("max_order_value", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("max_price_deviation_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("max_price_deviation_abs", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("max_orders_per_second", sa.Integer(), nullable=True),
        sa.Column("max_order_operations_per_second", sa.Integer(), nullable=True),
        sa.Column("max_orders_per_minute", sa.Integer(), nullable=True),
        sa.Column("max_orders_per_day", sa.Integer(), nullable=True),
        sa.Column("enable_freeze_qty_check", sa.Boolean(), nullable=True),
        sa.Column("skip_price_validation_for_exit", sa.Boolean(), nullable=True),
        sa.Column("max_orders_per_symbol_per_day", sa.Integer(), nullable=True),
        sa.Column("max_total_positions", sa.Integer(), nullable=True),
        sa.Column("max_buy_qty_per_symbol_per_day", sa.Integer(), nullable=True),
        sa.Column("max_sell_qty_per_symbol_per_day", sa.Integer(), nullable=True),
        sa.Column("max_buy_orders_per_day", sa.Integer(), nullable=True),
        sa.Column("max_sell_orders_per_day", sa.Integer(), nullable=True),
        sa.Column("max_position_qty_per_symbol", sa.Integer(), nullable=True),
        sa.Column("max_daily_loss_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("max_daily_loss_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("auto_square_off_on_breach", sa.Boolean(), nullable=True),
        sa.Column("enable_auto_kill_on_loss", sa.Boolean(), nullable=True),
        sa.Column("max_rejection_rate_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("max_vix_level", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("volatility_pause_minutes", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stale_price_seconds", sa.Integer(), nullable=True),
        sa.Column("early_market_grace_seconds", sa.Integer(), nullable=True),
        sa.Column("min_volume_early_period_seconds", sa.Integer(), nullable=True),
        sa.Column("min_open_interest", sa.Integer(), nullable=True),
        sa.Column("max_total_combos", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_rms_config_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rms_config")),
        sa.UniqueConstraint(
            "config_level",
            "exchange",
            "trading_client_id",
            "symbol",
            "segment_type",
            name="uq_rms_config_scope",
        ),
    )
    op.create_index(
        op.f("ix_rms_config_trading_client_id"), "rms_config", ["trading_client_id"], unique=False
    )
    op.create_table(
        "rms_daily_stats",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("trading_symbol", sa.String(length=100), nullable=False),
        sa.Column("stat_date", sa.Date(), nullable=False),
        sa.Column("order_count", sa.Integer(), nullable=True),
        sa.Column("buy_order_count", sa.Integer(), nullable=True),
        sa.Column("sell_order_count", sa.Integer(), nullable=True),
        sa.Column("buy_qty", sa.Integer(), nullable=True),
        sa.Column("sell_qty", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_rms_daily_stats_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "trading_client_id", "trading_symbol", "stat_date", name=op.f("pk_rms_daily_stats")
        ),
    )
    op.create_index(
        op.f("ix_rms_daily_stats_trading_client_id"),
        "rms_daily_stats",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "strategy_evaluation_log",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("log_id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=16), nullable=False),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("signals_generated", sa.Integer(), nullable=True),
        sa.Column("execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("result_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_strategy_evaluation_log_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_strategy_evaluation_log")),
    )
    op.create_index(
        op.f("ix_strategy_evaluation_log_trading_client_id"),
        "strategy_evaluation_log",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "subscription_state",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("state_id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("cycle_key", sa.String(length=64), nullable=True),
        sa.Column("state_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_evaluation_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_signal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evaluation_count", sa.Integer(), nullable=True),
        sa.Column("signal_count", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_subscription_state_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("state_id", name=op.f("pk_subscription_state")),
    )
    op.create_index(
        op.f("ix_subscription_state_trading_client_id"),
        "subscription_state",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capital", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("risk_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("absolute_max_risk", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=False),
        sa.Column("leverage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("max_active_positions", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_subscriptions_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("subscription_id", name=op.f("pk_subscriptions")),
    )
    op.create_index(
        op.f("ix_subscriptions_trading_client_id"),
        "subscriptions",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "trade_corporate_actions",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("corporate_action_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_id", sa.String(length=64), nullable=False),
        sa.Column("product", sa.String(length=16), nullable=False),
        sa.Column("qty_factor", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column("pre_snapshot", sa.Text(), nullable=False),
        sa.Column("post_snapshot", sa.Text(), nullable=False),
        sa.Column("qty_residue", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("credit_status", sa.String(length=16), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_trade_corporate_actions_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_corporate_actions")),
    )
    op.create_index(
        op.f("ix_trade_corporate_actions_trading_client_id"),
        "trade_corporate_actions",
        ["trading_client_id"],
        unique=False,
    )
    op.create_table(
        "trades",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("trade_id", sa.String(length=50), nullable=False),
        sa.Column("product", sa.String(length=16), nullable=False),
        sa.Column("combo_id", sa.String(length=64), nullable=True),
        sa.Column("leg_role", sa.String(length=32), nullable=True),
        sa.Column("brokerage_plan", sa.String(length=30), nullable=True),
        sa.Column("client_id", sa.String(length=30), nullable=True),
        sa.Column("strategy_name", sa.String(length=30), nullable=False),
        sa.Column("tranch_name", sa.String(length=30), nullable=True),
        sa.Column("group_name", sa.String(length=100), nullable=True),
        sa.Column("exchange", sa.String(length=15), nullable=True),
        sa.Column("segment", sa.String(length=15), nullable=True),
        sa.Column("trading_symbol", sa.String(length=50), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("product_type", sa.String(length=10), nullable=True),
        sa.Column("start_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("req_entry", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("req_exit", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("req_quantity", sa.Integer(), nullable=True),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("cmp", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("contract_multiplier", sa.Integer(), nullable=True),
        sa.Column("qty_per_lot", sa.Integer(), nullable=False),
        sa.Column("filled_quantity", sa.Integer(), nullable=True),
        sa.Column("initial_stoploss", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("stoploss", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("target", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("profit_loss", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("turnover_charges", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("brokerage_charges", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("sebi_charges", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("stt_charges", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("stamp_duty_charges", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("gst_charges", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("depository_charges", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("charges", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("net_profit_loss", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("pl_percentage", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("exit_reason", sa.String(length=30), nullable=True),
        sa.Column("failure_reason", sa.String(length=1000), nullable=True),
        sa.Column("is_futures", sa.Boolean(), nullable=True),
        sa.Column("is_options", sa.Boolean(), nullable=True),
        sa.Column("remarks", sa.String(length=500), nullable=True),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("mtf_interest", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("ca_factor", sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column("entry_sequence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_trades_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("trade_date", "trade_id", name=op.f("pk_trades")),
    )
    op.create_index(
        op.f("ix_trades_trading_client_id"), "trades", ["trading_client_id"], unique=False
    )
    op.create_table(
        "trading_client_login_status",
        sa.Column("trading_client_id", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("is_login_success", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("password_expiry_days", sa.Integer(), nullable=True),
        sa.Column("login_error", sa.Text(), nullable=True),
        sa.Column("access_token_encrypted", sa.Text(), nullable=True),
        sa.Column("public_token_encrypted", sa.Text(), nullable=True),
        sa.Column("request_token", sa.String(length=500), nullable=True),
        sa.Column("server_url", sa.String(length=500), nullable=True),
        sa.Column("session_created_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["trading_client_id"],
            ["trading_clients.id"],
            name=op.f("fk_trading_client_login_status_trading_client_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("trading_client_id", name=op.f("pk_trading_client_login_status")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trading_client_login_status")
    op.drop_index(op.f("ix_trades_trading_client_id"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(
        op.f("ix_trade_corporate_actions_trading_client_id"), table_name="trade_corporate_actions"
    )
    op.drop_table("trade_corporate_actions")
    op.drop_index(op.f("ix_subscriptions_trading_client_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_subscription_state_trading_client_id"), table_name="subscription_state")
    op.drop_table("subscription_state")
    op.drop_index(
        op.f("ix_strategy_evaluation_log_trading_client_id"), table_name="strategy_evaluation_log"
    )
    op.drop_table("strategy_evaluation_log")
    op.drop_index(op.f("ix_rms_daily_stats_trading_client_id"), table_name="rms_daily_stats")
    op.drop_table("rms_daily_stats")
    op.drop_index(op.f("ix_rms_config_trading_client_id"), table_name="rms_config")
    op.drop_table("rms_config")
    op.drop_index(
        op.f("ix_live_trades_archive_trading_client_id"), table_name="live_trades_archive"
    )
    op.drop_table("live_trades_archive")
    op.drop_index(op.f("ix_live_trades_trading_client_id"), table_name="live_trades")
    op.drop_table("live_trades")
    op.drop_index(
        op.f("ix_live_trade_signals_archive_trading_client_id"),
        table_name="live_trade_signals_archive",
    )
    op.drop_table("live_trade_signals_archive")
    op.drop_index(op.f("ix_live_trade_signals_trading_client_id"), table_name="live_trade_signals")
    op.drop_table("live_trade_signals")
    op.drop_index(op.f("ix_kill_switches_trading_client_id"), table_name="kill_switches")
    op.drop_table("kill_switches")
    op.drop_index(op.f("ix_eod_pnl_reports_trading_client_id"), table_name="eod_pnl_reports")
    op.drop_table("eod_pnl_reports")
    op.drop_index(op.f("ix_client_margins_trading_client_id"), table_name="client_margins")
    op.drop_table("client_margins")
    op.drop_index(op.f("ix_client_capital_trading_client_id"), table_name="client_capital")
    op.drop_table("client_capital")
    op.drop_index(
        op.f("ix_capital_change_history_trading_client_id"), table_name="capital_change_history"
    )
    op.drop_table("capital_change_history")
    op.drop_table("trailing_sl_policy")
    op.drop_table("trading_clients")
    op.drop_table("trade_log")
    op.drop_table("synthetic_candles")
    op.drop_table("symbols")
    op.drop_table("symbol_broker_info")
    op.drop_table("strike_selection_policy")
    op.drop_table("strategy_templates")
    op.drop_table("strategy_symbol_subscriptions")
    op.drop_table("strategy_rules_output")
    op.drop_table("strategy_rules_map")
    op.drop_table("strategy_indicator_rules")
    op.drop_table("strategy_definitions")
    op.drop_table("strategy_config")
    op.drop_table("strategy_breakout_watches")
    op.drop_table("straddle_candles")
    op.drop_table("stock_universes")
    op.drop_table("stock_universe_members")
    op.drop_table("statutory_charges_broker_overrides")
    op.drop_table("statutory_charges")
    op.drop_table("sl_target_policy")
    op.drop_table("rules")
    op.drop_table("rms_client_state")
    op.drop_table("rms_breach_log")
    op.drop_table("products")
    op.drop_table("pcr_candles")
    op.drop_table("order_fill_escalation_policy")
    op.drop_table("kill_switch_types")
    op.drop_table("iv_candles")
    op.drop_table("holidays")
    op.drop_table("hedge_schedules")
    op.drop_table("exit_policy")
    op.drop_table("exchanges")
    op.drop_index("ix_event_journal_type_day", table_name="event_journal")
    op.drop_index("ix_event_journal_correlation", table_name="event_journal")
    op.drop_index("ix_event_journal_aggregate", table_name="event_journal")
    op.execute(sa.text("DROP TABLE IF EXISTS event_journal"))
    op.execute(sa.text("DROP SEQUENCE IF EXISTS event_journal_sequence_seq"))
    op.drop_table("event_days")
    op.drop_table("data_provider_sessions")
    op.drop_table("daily_symbol_close_prices")
    op.drop_table("corporate_actions")
    op.drop_table("client_pnl_snapshots")
    op.drop_table("brokers")
    op.drop_table("brokerage_plans")
    op.drop_table("brokerage_plan_rates")
    op.drop_table("broker_exchange_config")
    op.drop_table("broker_api_stats")
    op.drop_table("audit_log")
    op.drop_table("app_config")
    op.drop_table("allocation_models")
    op.drop_table("allocation_model_strategies")
    op.drop_table("alerts")
    op.drop_table("aggregated_pnl_snapshots")
    # ### end Alembic commands ###
